version: 2
project_name: imscli
before:
  hooks:
    - go mod tidy
builds:
  - id: imscli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        formats: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Version }}-next"
# Group commits by conventional-commit prefix for cleaner release notes.
changelog:
  sort: asc
  groups:
    - title: Features
      regexp: '^.*?feat(\([^)]+\))?!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([^)]+\))?!?:.+$'
      order: 1
    - title: Other
      order: 999
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  "https://github.com/adobe/imscli"
    description: "A small CLI tool to interact with the Adobe IMS API"
    maintainer: "Jose Antonio Insua <insuafer@adobe.com>"
    license: "Apache 2.0"
    vendor: "github.com/adobe"
    section: default
    priority: extra
    formats:
    - apk
    - deb
    - rpm
